import type { ApolloClient } from '@apollo/client/core'

import { APOLLO_CLIENTS_KEY, omit } from '@vue3-apollo/core'
import { defineNuxtPlugin } from '#app'
// Generated by the module (maps clientId -> builder); always present.
import { clientConfigs } from '#build/apollo/client-configs'
import { defu } from 'defu'

import type { ApolloClientBuilder } from './defineApolloClient'

import { createApolloClient } from './utils/createApolloClient'

export default defineNuxtPlugin(async (nuxtApp) => {
    const runTimeconfig = nuxtApp.$config
    const apolloConfig = runTimeconfig.public.apollo

    if (!apolloConfig?.clients) {
        throw new Error('[vue3-apollo] No Apollo clients configured')
    }

    const builders = clientConfigs as Record<string, ApolloClientBuilder | undefined>

    // Create all clients in parallel
    const entries = await Promise.all(
        Object.entries(apolloConfig.clients).map(async ([clientId, config]) => {
            const client = await createApolloClient({
                clientId,
                config: defu(config, omit(apolloConfig, ['clients', 'autoImports'])),
                nuxtApp,
                setup: builders[clientId]
            })
            return [clientId, client] as const
        })
    )

    const apolloClients: Record<string, ApolloClient> = Object.fromEntries(entries)

    nuxtApp.vueApp.provide(APOLLO_CLIENTS_KEY, apolloClients)

    return {
        provide: {
            apolloClients
        }
    }
})
